web/app/forms/users.py
from flask_wtf import Form
from wtforms import TextField
from wtforms import Form, BooleanField, StringField, PasswordField, SubmitField, validators

class UserSignUpForm(Form):
    username = StringField('Username', [validators.Length(min=4, max=25)])
    email = StringField('Email Address', [validators.Length(min=6, max=35)])
    first_name = StringField('First Name', [validators.Length(min=6, max=35)])
    last_name = StringField('Last Name', [validators.Length(min=6, max=35)])
    password = PasswordField('New Password', [
        validators.DataRequired(),
        validators.EqualTo('confirm', message='Passwords must match')
    ])
    confirm = PasswordField('Confirm Password')
    submit = SubmitField('Submit')

class UserLoginForm(Form):
    email = StringField('Email Address', [validators.Length(min=6, max=35)])
    password = PasswordField('New Password', [
        validators.DataRequired(),
        validators.EqualTo('confirm', message='Passwords must match')
    ])
    submit = SubmitField('submit')

web/app/views/users.py
from flask import Blueprint, render_template, request, url_for, flash, redirect
from flask_login import login_user, login_required, current_user, logout_user, login_manager, UserMixin
from werkzeug.security import generate_password_hash, check_password_hash
from app import mongo,config
from app.login import User
from app.forms.users import UserLoginForm, UserSignUpForm
import yaml, requests, json
from app.utils import get_plot_locations, get_current_location, get_dest_list , get_death_list

from azure.storage.blob import BlockBlobService , ContentSettings

def load_config ():
    with open ('../config.yml') as f:
        config = yaml.load(f)
        return config 

config = load_config()
api = config['BING_API_KEY']

users = Blueprint('users', __name__)

block_blob_service = BlockBlobService(account_name = config['ACCOUNT_NAME'], account_key= config['BLOB_STORAGE_KEY'])


@users.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        login_data = request.form.to_dict()

        user = mongo.db.users.find_one(
            {'email': login_data['email'], 'role': 'user'})

        if user:
            if check_password_hash(user['password'], login_data['password']):
                user_obj = User(user)
                login_user(user_obj)
                flash('Login Successful')
                return redirect(url_for('users.dashboard', user=user['username']))
            else:
                flash("Incorrect Password")
                return redirect(url_for('users.login'))
        else:
            flash("Unauthorized Access")
            return redirect(url_for('users.login'))
    form = UserLoginForm()
    return render_template('users/login.html', title='Login', form=form)


@users.route('/signup', methods=['GET', 'POST'])
def signup():
    if request.method == 'POST':
        form_data = request.form.to_dict()

        pwd = form_data['password']
        hashed_pwd = generate_password_hash(pwd)

        form_data['password'] = hashed_pwd
        if mongo.db.users.find_one({'email': form_data['email']}) or mongo.db.users.find_one({'username': form_data['username']}):
            user = mongo.db.users.find_one({'email': form_data['email']})
            if user and user['role'] == 'user':
                flash("Username Exists, Try Again")

                return redirect(url_for('users.signup'))
        form_data['role'] = 'user'
        form_data.pop('confirm')
        mongo.db.users.update(
            {'username': form_data['username'], 'role': 'user'}, form_data, upsert=True)
        new_user = mongo.db.users.find_one(form_data)
        user = User(new_user)
        login_user(user)
        return redirect(url_for('users.dashboard', user=current_user.username))

    args = request.args
    form = UserSignUpForm()
 
    title = 'DiseaseWatch | Sign Up'
    if args:
        title = 'DiseaseWatch | Edit Profile'
        user = args.get('user')
        form_data = mongo.db.users.find_one({'username': user})
        form_data.pop('password')
        
    return render_template('users/signup.html',  
                            title = title, 
                            form = form,
                            )


@users.route('/logout')
@login_required
def logout():
    logout_user()
    flash('You have logged out.')
    return redirect(url_for('users.login'))


@users.route('/dashboard/<user>', methods=['GET', 'POST'])
@login_required
def dashboard(user):
    query = {'username': user, 'role': 'user'}
    user = mongo.db.users.find_one(query)

    choices = ['Anthrax', 'Cholera', 'Diphtheria', 'Dysentry', 'Food Poisoning', 'Hepatitis A', 'Leptospirosis', 'Malaria', 'Mumps', 'Polio', 'Rabies', 'Rubella', 'Smallpox', 'Tetanus', 'Tuberculosis']

    if request.method == "POST":
        position = request.json

        query = {'username': current_user.username}
        position['username'] = current_user.username

        if mongo.db.current_loc.find_one({'username': current_user.username}):
            mongo.db.current_loc.update(query,  position, upsert=True)
        else:
            mongo.db.current_loc.insert(position)

    return render_template ('users/dashboard.html', title = 'Home | {username}'.format(username=current_user.username), user=user, choices=choices)

    
@users.route('/nearme/<user>', methods=['GET', 'POST'])
@login_required
def nearme(user):

    current_location = get_current_location(current_user.username)
    dest_list, disease_count, all_locs = get_dest_list()

    death_dest_list, death_count = get_death_list()

    print(all_locs)
    data = {}
    origin_list = []
    origin_list.append(current_location)
    
    data["origins"] = origin_list
    data["destinations"] = dest_list
    data["travelMode"] = "driving"
   
    plot_locations = get_plot_locations(data, all_locs)
    print(plot_locations)

    return render_template('users/bing_map.html', api=api, current_location=current_location, plot_locations=plot_locations, disease_count=disease_count, death_count=death_count)
    
@users.route('/cityview/<user>',methods=['GET', 'POST'])
@login_required
def cityview(user):

    dest_list, disease_count, all_locs = get_dest_list()
    death_dest_list, death_count = get_death_list()

    if request.method == "POST":
        form_data = request.form.to_dict()
      
        form_data["latitude"] = form_data.pop('lat')
        form_data["longitude"] = form_data.pop('lng')
        current_location = form_data
        
        data = {}
        origin_list = []
        origin_list.append(form_data)
        
        data["origins"] = origin_list
        data["destinations"] = dest_list
        data["travelMode"] = "driving"

        plot_locations = get_plot_locations(data, dest_list)
       
    return render_template('users/bing_map.html', api=api, current_location=current_location, plot_locations=plot_locations, disease_count=disease_count, death_count=death_count)


@users.route('/globalmap/<user>',methods=['GET', 'POST'])
@login_required
def globalmap(user):

    current_location = get_current_location(current_user.username)
    dest_list, disease_count, all_locs = get_dest_list()
    death_dest_list, death_count = get_death_list()
    
    return render_template('users/bing_map.html', api=api, current_location=current_location, plot_locations=dest_list, disease_count=disease_count, death_count=death_count)
    

@users.route('/viewresults/<user>',methods=['GET', 'POST'])
@login_required
def viewresults(user):

    if request.method == 'POST':
        form_data = request.form.to_dict()
        print(form_data)
        query = form_data['query']
        query = query.lower()
        query = query.replace(' ', '_')
        url = 'https://diseasewatch.blob.core.windows.net/pdfs/' + query + '.jpg'
        
        return render_template('users/results.html' , url=url)

web/app/templates/users/base.html
<html>
<head>
    <title> {{ title }}</title>
    <meta name="viewport" content="width=device-width, height=device-height,initial-scale=1">
    <!-- Latest compiled and minified CSS -->
    <link rel="icon" href="{{ url_for('static', filename='img/icon.png' ) }}">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <!-- jQuery library -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <!-- Latest compiled JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/style.css' ) }}">
    <link href="https://afeld.github.io/emoji-css/emoji.css" rel="stylesheet">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.4.0/Chart.min.js"></script>

</head>

<body class="users" >

    <nav class="navbar navbar-inverse navbar-users">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{{ url_for('index')}}">DiseaseWatch</a>
            </div>
            <div class="collapse navbar-collapse" id="myNavbar">
                <ul class="nav navbar-nav">
                    {% if current_user.is_authenticated %}
                    <li class="active">
                        <a href="{{ url_for('users.dashboard', user=current_user.username) }}"> <span class="glyphicon glyphicon-home"></span> Home</a>
                    </li>
                    {% endif %}
                </ul>
                <ul class="nav navbar-nav navbar-right">
                        {% if current_user.is_authenticated %}
                                 
                        <li>
                                <a href="{{ url_for('users.logout') }}">
                                    <span class="glyphicon glyphicon-log-out"></span> Logout</a>
                            </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>
    <div class="page-wrap">
    {% block body %}
    {% endblock %}
    </div>
    <footer class="container-fluid text-center site-footer footer-users">
        <h5>
            Contact us
        </h5>
        <h6>
            <a href="https://www.linkedin.com/in/ashmita-raju-0a0839115/">Ashmita Raju</a> | 
            <a href="https://www.linkedin.com/in/aravindbs">Aravind B S</a> 
        </h6>
        <h6>
            <img id="github-logo" src="{{ url_for('static', filename='img/GitHub-Mark-Light-32px.png') }}">
            <a href="https://github.com/aravindbs/cfdpp2018">Source Code</a>
        <h6>
    </footer>

</body>


</html>

web/app/templates/users/bing_map.html
{% extends "users/base.html" %} {% block body %}

    <script type='text/javascript'
            src='https://www.bing.com/api/maps/mapcontrol?callback=GetMap'
            async defer></script>
    <script type='text/javascript'>
    function GetMap() {
        var map = new Microsoft.Maps.Map('#myMap', {
            credentials: '{{ api }}',
            center: new Microsoft.Maps.Location({{ current_location.latitude }}, {{ current_location.longitude}})
        });

        infobox = new Microsoft.Maps.Infobox(map.getCenter(), {
            visible: false
        });

        infobox.setMap(map);

        var center = map.getCenter();

        var pin = new Microsoft.Maps.Pushpin(center, { color: 'blue' });
        pin.metadata = { title : 'Current Location'};
        Microsoft.Maps.Events.addHandler(pin, 'click', pushpinClicked);
        map.entities.push(pin);

        var latlongs = JSON.parse('{{ plot_locations | tojson }}');
        var disease_count = JSON.parse('{{ disease_count | tojson }}');
        var death_count = JSON.parse('{{ death_count | tojson }}');

        var locs = [];
        
        for(var i=0,len = latlongs.length;i<len;i++){
            
            var newElement = {}
            newElement = new Microsoft.Maps.Location(latlongs[i].latitude, latlongs[i].longitude)
            locs.push(newElement);
            var temp = latlongs[i].place_id;

            for (var key in disease_count) 
            {
                if(key == temp) 
                    value = disease_count[key]; 
            }

            for (var key in death_count) 
            {
                if(key == temp) 
                    value2 = disease_count[key]; 
            }

            var value = JSON.stringify(value); 
            var value2 = JSON.stringify(value2); 
            console.log(value2);
            value = value.replace('{' , '').replace('}', '').replace(/"/g, ''); 
            if (value2)
            {  
                value2 = value2.replace('{' , '').replace('}', '').replace(/"/g, ''); 
                var pin = new Microsoft.Maps.Pushpin(new Microsoft.Maps.Location(latlongs[i].latitude, latlongs[i].longitude) , { color : 'red'});
                pin.metadata = {
                
                title: latlongs[i].loc_name,
                description: 'DISEASES:' + value + '\n\nDEATHS:' + value2
            }
            }
            else {
                
                var pin = new Microsoft.Maps.Pushpin(new Microsoft.Maps.Location(latlongs[i].latitude, latlongs[i].longitude) , { color : 'red'});
                pin.metadata = {
                
                title: latlongs[i].loc_name,
                description: 'DISEASES:' + value 
            }
            }
            Microsoft.Maps.Events.addHandler(pin, 'click', pushpinClicked);
            map.entities.push(pin);
        }
        locs.push(center)
        var bounds = Microsoft.Maps.LocationRect.fromLocations(locs);
        map.setView({bounds:bounds, padding: 100});

    }

    function pushpinClicked(e) {
        //Make sure the infobox has metadata to display.
        if (e.target.metadata) {
            //Set the infobox options with the metadata of the pushpin.
            infobox.setOptions({
                location: e.target.getLocation(),
                title: e.target.metadata.title,
                description: e.target.metadata.description,
                visible: true
            });
        }
    }
    </script>


    <div id="myMap" style="position:relative;width:80%;height:80%;left:10%;right:10%">
    </div>

    <a href="{{ url_for('users.dashboard', user=current_user.username) }}"class="btn btn-info"> Back to Dashboard</a>

    {% endblock %}
</html>

web/app/templates/users/dashboard.html
{% extends "users/base.html" %} {% block body %}
<div class="modal fade" id="city" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title" id="myModalLabel">Enter Location</h4>
            </div>
            <div class="modal-body">
                <div class="map_canvas"></div>
                <form id="form-body" class="form-horizontal" method="post" action="{{ url_for('users.cityview' , user = current_user.username)}}"
                    enctype="multipart/form-data">

                    <label class="control-label col-sm-2">Location</label>
                    <div id="pac-container">
                        <input class="form-control" id="geocomplete" name="loc_name" type="text" placeholder="Type in a location" />
                    </div>
                    <input type="hidden" class="form-control" name="lat" type="text" value="">
                    <input type="hidden" class="form-control" name="lng" type="text" value="">

                    <button type="submit" form="form-body" class="btn btn-success" value="Submit">Submit</button>

                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-danger btn-simple" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>


<div class="modal fade" id="results" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title" id="myModalLabel">What would you like to search for?</h4>
            </div>
            <div class="modal-body">
                <div class="map_canvas"></div>
                <form id="form2" class="form-horizontal" method="post" action="{{ url_for('users.viewresults' , user = current_user.username)}}"
                    enctype="multipart/form-data">

                    <label class="control-label col-sm-2">Search</label>
                    <select name="query" id="query">   
                        {% for input in choices%}
                            <option  value="{{input}}">{{input}}</option>
                        {% endfor %}
                    </select>
                    <button type="submit" form="form2" class="btn btn-success" value="Submit">Submit</button>

                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-danger btn-simple" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>

<div class="container-fluid text-center main-body">
    <div class="row content text-center">

        <div class="col-sm-6 col-sm-offset-3">
            <div class="well">
                <img src="https://avatars.io/avatar/HASH/size" class="img-circle" height="65" width="65" alt="Avatar">
                <h3 class="semi-bold-black">{{ user.first_name }} {{ user.last_name }}</h3>
                <h4 class="semi-bold-black"> {{ user.role }} </h4>
                <p class="font-lightitalic">@{{ user.username }}</p>

            </div>
        </div>
        <div class="col-sm-6 col-sm-offset-3">
            
                <a href="{{ url_for('users.nearme', user=current_user.username) }}" class="btn btn-info btn-dash"
                    data-toggle="tooltip" title="Check for outbreaks of diseases near your current location.">
                    Outbreaks Near Me </a>
                <span data-toggle="modal" data-target="#city">
                    <a class="btn btn-info btn-dash" data-toggle="tooltip" title="Check for outbreaks of diseases in a particular city.">Outbreaks
                        in a City </a>
                </span>
                <a href="{{ url_for('users.globalmap', user=current_user.username) }}" class="btn btn-info btn-dash"
                    data-toggle="tooltip" title="Check for outbreaks all over the world."> Global Map </a>
                <span data-toggle="modal" data-target="#results">
                    <a class="btn btn-info btn-dash" data-toggle="tooltip" title="Get information about a disease.">Disease Information </a>
                </span>


        </div>
    </div>
</div>
<script>
    window.onload = function () {
        getLocation();
    };
    function getLocation() {
        if (navigator.geolocation) {
            navigator.geolocation.getCurrentPosition(savePosition);
        } else {
            x.innerHTML = "Geolocation is not supported by this browser.";
        }
    }
    function savePosition(position) {
        var latitude = position.coords.latitude
        var longitude = position.coords.longitude;

        var position =
        {
            'latitude': latitude,
            'longitude': longitude
        }
        var url = "/dashboard/" + "{{current_user.username|safe}}"
        $.ajax({
            url: url,
            type: 'POST',
            data: JSON.stringify(position),   // converts js value to JSON string
            contentType: 'application/json; charset=utf-8',
            dataType: 'json',
            async: false,
        }).done(function (result) { console.log(result) })

    }

</script>

<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyD17OTqHh1iI6T_8uSGlO_0SXjymIQJGVU&libraries=places""></script>
<script src="
    http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js"> </script> <script src="{{ url_for('static', filename='js/jquery.geocomplete.js' ) }}"></script>
<script src="{{ url_for('static', filename='js/geocomplete.js' ) }}"></script>


<style>
    .pac-container {
        padding-bottom: 12px;
        margin-right: 12px;
        z-index: 99999 !important;
    }
</style>
{% endblock %}

web/app/templates/users/login.html
{% extends "users/base.html" %} {% block body %}
<div class="container-fluid text-center">
    <div class="row content text-center">
        <div id="form-container" class='col-sm-6 col-sm-offset-3'>
            <div id="form-title">
                <h4> Log In</h4>
            </div>
            <form id="form-body" class="form-horizontal" method="post" action="{{ url_for('users.login') }}" enctype="multipart/form-data">
                <div class="form-group">
                    <label class="control-label col-sm-2" for="email">Email:</label>
                    <div class="col-sm-10">
                        <input type="email" name="email" class="form-control" id="email" placeholder="Enter email"
                            required="required">
                    </div>
                </div>
                <div class="form-group">
                    <label class="control-label col-sm-2" for="password">Password:</label>
                    <div class="col-sm-10">
                        <input type="password" name="password" class="form-control" id="pwd" placeholder="Enter password"
                            required="required">
                    </div>
                </div>
                <div class="form-group">
                    <div "col-sm-10">
                        <button type="submit" class="btn btn-success">Submit</button>
                    </div>
                </div>
            </form>
            {% with messages = get_flashed_messages() %}
            {% if messages %}
            <div id="form-title">
                {% for message in messages %}
                <p>{{ message }}</p> <br>
                {% endfor %}
            </div>
            {% endif %} {% endwith %}
        </div>
    </div>
</div>
{% endblock %}

web/app/templates/users/results.html
{% extends "users/base.html" %} {% block body %}
<div class="container-fluid text-center">
    <div class="row content text-center">
<div class="col-sm-8 col-sm-offset-2">
<img class="results-image" src="{{ url }}" > 
</div>
<div class="col-sm-12"></div>
<a href="{{ url_for('users.dashboard', user=current_user.username) }}"class="btn btn-info"> Back to Dashboard</a>
</div>
</div>
</div>
{% endblock %}

web/app/templates/users/signup.html
{% extends "users/base.html" %} {% block body %}
<div class="container-fluid text-center main-body">
    <div class="row content text-center">
        <div id="form-container" class='col-sm-8 col-sm-offset-2'>
            <div id="form-title">
               
                <h4>Sign Up</h4>
               
            </div>
            <form id="form-body" class="form-horizontal" method="post" action="{{ url_for('users.signup') }}" enctype="multipart/form-data">
                {% for field in form %}
                <div class="form-group">
                    {% if field.name == 'submit' %}
                    <div class="form-group">
                        <div class="col-sm-12">
                           {{ field(class='btn btn-success') }}
                        </div>
                    </div>
                    {% else %}
                    <label class="control-label col-sm-2">{{ field.label }}</label>
                    <div class="col-sm-10">
                        {{ field(class='form-control') }}
                    </div>
                    {% endif %}
                </div>
                {% endfor %}
            </form>
            {% with messages = get_flashed_messages() %}
            {% if messages %}
            <div id="form-title">

                {% for message in messages %}
                <p>{{ message }}</p> <br>
                {% endfor %}
            </div>
            {% endif %} {% endwith %}

        </div>
    </div>
</div>
{% endblock %}